/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inhertiance;

public class Library {
    public static void main(String[] args) {
        Resturant resturant=new Resturant("KFC","$$$");

        resturant.addReview(new Review("","",4));
        System.out.println(resturant.reviews);
    }


}
