/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.io.BufferedReader;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;


public class App {

    public static void main(String[] args) {

        Path filePath = Paths.get("src/main/resources/gates.js");
        jsLinter(filePath);
    }

   
    public static void jsLinter(Path path) {

        try (BufferedReader br = Files.newBufferedReader(path)){

            String currentLine = "";
            int lineNumber = 0;

            while(currentLine != null) {
                if(checkErrorValid(currentLine)) {
                    System.out.println("Line " + lineNumber + ": Missing semicolon.");
                }
                lineNumber++;
                currentLine = br.readLine();
            }
        } catch (IOException e) {
            System.out.println(e);
        }


    }

    
    private static boolean checkErrorValid(String line) {

        if(line.isBlank() || line.isEmpty() || line.endsWith("{") || line.endsWith("}") || line.contains("if") || line.contains("else")) {
            return false;
        }
        return true;
    }


}
