/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary.basiclibrary;

import java.util.Arrays;

public class App {

    public static void main(String[] args) {
        int[] arr = { 1, 3, 4 };
        double[] doubleArr = { 1, 3, 4 };
        roll(5);
        System.out.println(containsDuplicates(arr));
       calculatingAverages(doubleArr);
       int[][] weeklyMonthTemperatures = {
        {66, 64, 58, 65, 71, 57, 60},
        {57, 65, 65, 70, 72, 65, 51},
        {55, 54, 60, 53, 59, 57, 61},
        {65, 56, 55, 52, 55, 62, 57}
};
arraysOfArrays(weeklyMonthTemperatures);

    }

    public static void roll(int n) {
        int[] diceRollingValues = new int[n];
        for (int i = 0; i < n; i++) {
            int diceValue = (int) Math.floor(Math.random() * 6 + 1);
            diceRollingValues[i] = diceValue;
        }
        System.out.println(Arrays.toString(diceRollingValues));
    }

    public static boolean containsDuplicates(int[] arr) {
        for (int i = 0; i < arr.length; i++) {
            for (int j = 0; j < arr.length; j++) {
                if (i != j) {
                    if (arr[i] == (arr[j])) {
                        return true;

                    }

                }
            }
        }
        return false;
    }

    public static void calculatingAverages(double[] arr) {
        int sum = 0;
        for (double el:arr) {
            sum +=el;
        }
       float  avg = (float)sum / (arr.length);
        System.out.println(avg); 
    }

    public static void arraysOfArrays(int[][] arr) {
        int[] tempArr = new int[arr[0].length];
        double sum = 0;
        double avg =0;
        double temp = 2147483647;
        for (int i = 0; i < arr.length; i++) {
            for (int j = 0; j < arr[i].length; j++) {
                sum += arr[i][j];
            }
            
            avg =sum/ arr[i].length;
            sum=0;
            System.out.println(avg);
            if (avg < temp) {
                for (int j = 0; j < arr[i].length; j++) {
                    tempArr[j] = arr[i][j];
                }
                temp= avg;
            }
        }
        System.out.println(Arrays.toString(tempArr));
    }
}
